# Generated by Django 4.2.3 on 2025-06-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Judul halaman, contoh: 'Tentang Kami'", max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL unik, akan terisi otomatis dari judul.', max_length=200, unique=True)),
                ('content', models.TextField(help_text='Isi utama dari halaman. Anda bisa menggunakan HTML.')),
                ('header_image', models.ImageField(blank=True, help_text='Gambar banner opsional.', null=True, upload_to='informasi/headers/')),
                ('is_published', models.BooleanField(default=True, help_text='Centang untuk menampilkan halaman ini.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='Contoh: Founder & CEO', max_length=100)),
                ('bio', models.TextField(blank=True, help_text='Deskripsi singkat tentang anggota tim.')),
                ('photo', models.ImageField(help_text='Foto profil.', upload_to='team/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Urutan tampil (0 akan tampil pertama).')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
