# Generated by Django 4.2.3 on 2025-06-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(help_text='Isi utama dari halaman. Anda bisa menggunakan HTML di sini.'),
        ),
        migrations.AlterField(
            model_name='page',
            name='header_image',
            field=models.ImageField(blank=True, help_text='Gambar banner opsional untuk bagian atas halaman.', null=True, upload_to='informasi/headers/'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Centang untuk menampilkan halaman ini di situs.'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL unik (contoh: tentang-kami). Biarkan kosong agar terisi otomatis.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(help_text='Foto profil anggota tim.', upload_to='team/'),
        ),
    ]
