# Generated by Django 4.2.3 on 2025-06-21 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='komenatr',
            new_name='komentar',
        ),
    ]
