# Generated by Django 4.2.3 on 2025-06-22 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto_ktp',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='ktp/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='selfie_ktp',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='selfie_ktp/'),
            preserve_default=False,
        ),
    ]
