# Generated by Django 4.2.3 on 2025-06-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='foto_produk',
            field=models.ImageField(blank=True, null=True, upload_to='produk/'),
        ),
    ]
