# Generated by Django 4.2.3 on 2025-06-20 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toko', '0002_produk_foto_produk'),
    ]

    operations = [
        migrations.CreateModel(
            name='KomentarToko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('toko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentar', to='toko.toko')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
